### ISSUE TITLE
Connecting with SSH timed out

### ISSUE THREAD

**Issue by raine-works** [loft-sh/devpod#1031]
**What happened?**  
Attempting to connect to provider remote host via SSH times out with error: "Waiting for Devpod agent to come up..." Cannot connect via SSH with VSCode or the terminal. The Devpod CLI SSH command works as intended. 

**What did you expect to happen instead?**  
Devcontainer to be accessible via SSH. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
	"name": "Homelab",
	"build": {
		"dockerfile": "Dockerfile",
		"context": ".",
		"args": {
			"USERNAME": "${localEnv:USER}"
		}
	},
	"remoteUser": "${localEnv:USER}",
	"features": {
		"ghcr.io/devcontainers/features/github-cli:1": {}
	},
	"forwardPorts": [3000],
	"otherPortsAttributes": {
		"onAutoForward": "ignore"
	},
	"mounts": [
		"source=${env:HOME}${env:USERPROFILE}/.config/gh,target=/home/${localEnv:USER}/.config/gh,type=bind",
		"source=${env:HOME}${env:USERPROFILE}/.ssh,target=/home/${localEnv:USER}/.ssh,type=bind"
	],
	"postAttachCommand": "git config --global diff.tool ...",
	"postStartCommand": "pnpm config set store-dir ~/.pnpm-store && pnpm setup",
	"customizations": {
		"vscode": {
			"extensions": [
				"esbenp.prettier-vscode",
				"yoavbls.pretty-ts-errors",
				"dbaeumer.vscode-eslint",
				"bradlc.vscode-tailwindcss",
				"eamodio.gitlens",
				"ms-azuretools.vscode-docker"
			]
		}
	},
	"runArgs": ["--network=host"]
}
```

**Local Environment:**  
- `devpod 0.0.5`
- Operating System: windows 
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Remote provider: ssh

**Anything else we need to know?**  
I am able to connect to the remote host via SSH directly. 

Docker engine on remote host has the following custom remote access config:
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://virgo.lab.raineworks.com:2375
```

**Comment by pascalbreuninger** [comment]
@raine-works are you experiencing the same problem with the latest v0.5.6 release?

**Comment by raine-works** [comment]
I updated to v0.5.6 and I am still seeing the same error.

```
PS C:\Users\Raine> ssh homelab.devpod
13:40:39 info Waiting for devpod agent to come up...
13:41:02 info Waiting for devpod agent to come up...
```

I tried deleted that workspace and creating a new one after updating. I am seeing the same results. The devpod cli ssh command works but the standard ssh command does not.

**Comment by 89luca89** [comment]
Hi @raine-works can you please to a test for me?

Can you open the ssh config file (It should be `$HOME\.ssh\config` also on windows) and add a `--debug` to the ProxyCommand of devpod?

Like:

```conf
...
...
  ProxyCommand devpod ssh --debug --stdio --context default --user vscode distrobox
  User vscode
```

So we can get some more useful logs from your command?

**Comment by raine-works** [comment]
Here is my SSH config. 

```
# DevPod Start hukt.devpod
Host hukt.devpod
  ForwardAgent yes
  LogLevel error
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  HostKeyAlgorithms rsa-sha2-256,rsa-sha2-512,ssh-rsa
  ProxyCommand "C:\Program Files\DevPod\devpod-cli.exe" ssh --debug --stdio --context default --user raine hukt
  User raine
# DevPod End hukt.devpod

Host virgo.lab.raineworks.com
  HostName virgo.lab.raineworks.com
  User raine
```

Here are the logs I am seeing after adding the --debug flag.

```
PS C:\Users\Raine> ssh hukt.devpod
12:21:05 debug Adding ssh keys to agent, disable via 'devpod context set-options -o SSH_ADD_PRIVATE_KEYS=false'
12:21:05 debug Run ssh-add C:\Users\Raine\.ssh\id_rsa
12:21:05 debug Error adding key C:\Users\Raine\.ssh\id_rsa to agent: Error connecting to agent: No such file or directory

exit status 2
12:21:05 debug Acquire workspace lock...
12:21:05 debug Acquired workspace lock...
12:21:05 debug execute inject script
12:21:05 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
12:21:05 debug Run command provider command: ${SSH_PROVIDER} command
12:21:25 debug done inject
12:21:25 debug done injecting
12:21:25 info Waiting for devpod agent to come up...
```

**Comment by 89luca89** [comment]
Thanks @raine-works 
can you update the ssh provider to the latest version? we implemented some fixes for how it behaves and those could potentially help for this issue

**Comment by raine-works** [comment]
I assume this can be done by deleting the provider and recreating it? I did that and Its still not working but I am seeing a different error message. 

```
PS C:\Users\Raine> ssh hukt.devpod
10:17:58 debug Adding ssh keys to agent, disable via 'devpod context set-options -o SSH_ADD_PRIVATE_KEYS=false'
10:17:58 debug Run ssh-add C:\Users\Raine\.ssh\id_rsa
10:17:58 debug Error adding key C:\Users\Raine\.ssh\id_rsa to agent: Error connecting to agent: No such file or directory

exit status 2
10:17:58 debug Acquire workspace lock...
10:17:58 debug Acquired workspace lock...
10:17:58 debug execute inject script
10:17:58 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:17:58 debug Run command provider command: ${SSH_PROVIDER} command
10:18:18 debug done inject
10:18:18 debug done injecting
10:18:18 info Waiting for devpod agent to come up...
10:18:18 debug Inject Error: context deadline exceeded
10:18:18 debug done exec
10:18:21 debug execute inject script
10:18:21 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:18:21 debug Run command provider command: ${SSH_PROVIDER} command
10:18:41 debug done inject
10:18:41 debug done injecting
10:18:41 info Waiting for devpod agent to come up...
```

**Comment by 89luca89** [comment]
Can you post it?

**Comment by raine-works** [comment]
```
PS C:\Users\Raine> ssh hukt.devpod
11:53:18 debug Adding ssh keys to agent, disable via 'devpod context set-options -o SSH_ADD_PRIVATE_KEYS=false'
11:53:18 debug Run ssh-add C:\Users\Raine\.ssh\id_rsa
11:53:18 debug Error adding key C:\Users\Raine\.ssh\id_rsa to agent: Error connecting to agent: No such file or directory

exit status 2
11:53:18 debug Acquire workspace lock...
11:53:18 debug Acquired workspace lock...
11:53:18 debug execute inject script
11:53:18 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
11:53:18 debug Run command provider command: ${SSH_PROVIDER} command
11:53:38 debug done inject
11:53:38 debug done injecting
11:53:38 info Waiting for devpod agent to come up...
11:53:38 debug Inject Error: context deadline exceeded
11:53:38 debug done exec
11:53:41 debug execute inject script
11:53:41 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
11:53:41 debug Run command provider command: ${SSH_PROVIDER} command
```

```
Host hukt.devpod
  ForwardAgent yes
  LogLevel error
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  HostKeyAlgorithms rsa-sha2-256,rsa-sha2-512,ssh-rsa
  ProxyCommand "C:\Program Files\DevPod\devpod-cli.exe" ssh --debug --stdio --context default --user raine hukt
  User raine
# DevPod End hukt.devpod

Host virgo.lab.raineworks.com
  HostName virgo.lab.raineworks.com
  User raine
```

**Comment by shanman190** [comment]
@raine-works, what OpenSSH version are you using? `ssh -V`

The default OpenSSH version from Windows is _VERY_ old, so downloading the latest release from [PowerShell/Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) is probably necessary. Alternatively, if you don't make use of the SSH agent, you can disable the Windows service to fix it as well.

**Comment by raine-works** [comment]
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

**Comment by raine-works** [comment]
I updated to OpenSSH version 9.5.
```
PS C:\Users\Raine> ssh -V
OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
```

I am still seeing the same error.
```
PS C:\Users\Raine> ssh hukt.devpod
10:49:24 debug Adding ssh keys to agent, disable via 'devpod context set-options -o SSH_ADD_PRIVATE_KEYS=false'
10:49:24 debug Run ssh-add C:\Users\Raine\.ssh\id_rsa
10:49:24 debug Acquire workspace lock...
10:49:24 debug Acquired workspace lock...
10:49:24 debug execute inject script
10:49:24 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:49:24 debug Run command provider command: ${SSH_PROVIDER} command
10:49:44 debug done inject
10:49:44 debug done injecting
10:49:44 info Waiting for devpod agent to come up...
10:49:44 debug Inject Error: context deadline exceeded
10:49:44 debug done exec
10:49:47 debug execute inject script
10:49:47 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:49:47 debug Run command provider command: ${SSH_PROVIDER} command
```

**Comment by shanman190** [comment]
So that "error" might happen a couple of times while the agent process is getting started. Then it normally goes away once the agent is ready to accept commands. Does it just continue to spin like that indefinitely?

**Comment by raine-works** [comment]
The longest I've let it run is for about 5 minutes.
```
PS C:\Users\Raine> ssh hukt.devpod
10:57:09 debug Adding ssh keys to agent, disable via 'devpod context set-options -o SSH_ADD_PRIVATE_KEYS=false'
10:57:09 debug Run ssh-add C:\Users\Raine\.ssh\id_rsa
10:57:09 debug Acquire workspace lock...
10:57:09 debug Acquired workspace lock...
10:57:09 debug execute inject script
10:57:09 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:57:09 debug Run command provider command: ${SSH_PROVIDER} command
10:57:29 debug done inject
10:57:29 debug done injecting
10:57:29 info Waiting for devpod agent to come up...
10:57:29 debug Inject Error: context deadline exceeded
10:57:29 debug done exec
10:57:32 debug execute inject script
10:57:32 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:57:32 debug Run command provider command: ${SSH_PROVIDER} command
10:57:52 debug done inject
10:57:52 debug done injecting
10:57:52 info Waiting for devpod agent to come up...
10:57:52 debug Inject Error: context deadline exceeded
10:57:52 debug done exec
10:57:55 debug execute inject script
10:57:55 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:57:55 debug Run command provider command: ${SSH_PROVIDER} command
10:58:15 debug done inject
10:58:15 debug done injecting
10:58:15 info Waiting for devpod agent to come up...
10:58:15 debug Inject Error: context deadline exceeded
10:58:15 debug done exec
10:58:18 debug execute inject script
10:58:18 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:58:18 debug Run command provider command: ${SSH_PROVIDER} command
10:58:38 debug done inject
10:58:38 debug done injecting
10:58:38 info Waiting for devpod agent to come up...
10:58:38 debug Inject Error: context deadline exceeded
10:58:38 debug done exec
10:58:41 debug execute inject script
10:58:41 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:58:41 debug Run command provider command: ${SSH_PROVIDER} command
10:59:01 debug done inject
10:59:01 debug done injecting
10:59:01 info Waiting for devpod agent to come up...
10:59:01 debug Inject Error: context deadline exceeded
10:59:01 debug done exec
10:59:04 debug execute inject script
10:59:04 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:59:04 debug Run command provider command: ${SSH_PROVIDER} command
10:59:24 debug done inject
10:59:24 debug done injecting
10:59:24 info Waiting for devpod agent to come up...
10:59:24 debug Inject Error: context deadline exceeded
10:59:24 debug done exec
10:59:27 debug execute inject script
10:59:27 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:59:27 debug Run command provider command: ${SSH_PROVIDER} command
10:59:47 debug done inject
10:59:47 debug done injecting
10:59:47 info Waiting for devpod agent to come up...
10:59:47 debug Inject Error: context deadline exceeded
10:59:47 debug done exec
10:59:50 debug execute inject script
10:59:50 debug download agent from https://github.com/loft-sh/devpod/releases/download/v0.5.6
10:59:50 debug Run command provider command: ${SSH_PROVIDER} command
11:00:10 debug done inject
11:00:10 debug done injecting
11:00:10 info Waiting for devpod agent to come up...
11:00:10 debug Inject Error: context deadline exceeded
11:00:10 debug done exec
```

**Comment by Sword-Breaker** [comment]
I think there is a typo in 'https://github.com/loft-sh/devpod/releases/download/v0.5.6', the URL is 404.

**Comment by shanman190** [comment]
So that download URL is just the first fragment. The file name gets appended to it based upon the target systems OS and architecture. 

It was a little misleading when I was debugging that area as well, but that part is just fine from what I've seen.

**Comment by raine-works** [comment]
I remote the agent from the remote machine and tried re-creating the workspace. The agent was successfully re-installed on the remote machine, but still hangs when trying to open a connection.

**Comment by raine-works** [comment]
I find it strange that the devpod cli ssh command can connect to the remote devcontainer but open-ssh in powershell can't. 

```
PowerShell 7.4.2

Raine  ~  ♥ 16:04  ssh node-test.devpod
16:04:29 info Waiting for devpod agent to come up...
16:04:52 info Waiting for devpod agent to come up...
16:05:15 info Waiting for devpod agent to come up...
16:05:38 info Waiting for devpod agent to come up...
16:06:01 info Waiting for devpod agent to come up...
16:06:24 info Waiting for devpod agent to come up...
16:06:47 info Waiting for devpod agent to come up...
16:07:10 info Waiting for devpod agent to come up...
16:07:33 info Waiting for devpod agent to come up...
16:07:56 info Waiting for devpod agent to come up...
16:08:19 info Waiting for devpod agent to come up...
16:08:42 info Waiting for devpod agent to come up...
16:09:05 info Waiting for devpod agent to come up...
16:09:28 fatal connect to server: timeout waiting for instance connection: context deadline exceeded

Raine  ~  ♥ 16:09  devpod node-test
16:10:35 error Try using the --debug flag to see a more verbose output
16:10:35 fatal unknown command "node-test" for "devpod"

Raine  ~  ♥ 16:10  devpod ssh node-test
node ➜ ~ $ ls
node ➜ ~ $ ls -a
.   .bash_logout  .cache   .docker     .npm        .profile        .zprofile
..  .bashrc       .config  .gitconfig  .oh-my-zsh  .vscode-server  .zshrc
node ➜ ~ $ cd /workspaces/
node ➜ /workspaces $ ls
node-test
node ➜ /workspaces $ cd node-test/
node ➜ /workspaces/node-test (main) $ ls
CODE_OF_CONDUCT.md  LICENSE  README.md  SECURITY.md  node_modules  package.json  server.js  yarn.lock
node ➜ /workspaces/node-test (main) $ npm run start

> docker_web_app@1.0.0 start
> node server.js

Running on http://0.0.0.0:3000
```

**Comment by raine-works** [comment]
I copied the SSH config from the Windows file system and pasted it on the SSH config in WSL. I adjusted the proxy command to use /mnt/c.

```
# DevPod Start node-test.devpod
Host node-test.devpod
  ForwardAgent yes
  LogLevel error
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  HostKeyAlgorithms rsa-sha2-256,rsa-sha2-512,ssh-rsa
  ProxyCommand "/mnt/c/Program Files/DevPod/devpod-cli.exe" ssh --stdio --context default --user node node-test
  User node
# DevPod End node-test.devpod
```

In WSL it worked immediately. 

```
OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
```

```
OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022
```

The issue must be related to the open-ssh version.

**Comment by thomasxd24** [comment]
@raine-works try using the new version of the ssh provider, I had the same problem as you. The new version fixed the problem for me.

(Even though it introduced another bug :/)

**Comment by raine-works** [comment]
Hallelujah! It works!!!!
