### ISSUE TITLE
postCreateCommand doesn't run in the right context?

### ISSUE THREAD

**Issue by cgestes** [loft-sh/devpod#1084]
**What happened?**  
```
[16:37:48] debug Run post create commands...
[16:37:48] info Run command : ./bash/local/codespaces_init.sh...
[16:37:48] debug Executing command : [su codespace -c ./bash/local/codespaces_init.sh]...
[16:37:48] error ./bash/local/codespaces_init.sh: line 3: pyenv: command not found
```

pyenv is installed in our Dockerfile, it is working in codespace.

**What did you expect to happen instead?**  
pyenv should be found.

.devcontainer:
```
{
	"build": {
		"dockerfile": "../Dockerfile"
	},
	"postCreateCommand": "./bash/local/codespaces_init.sh"
}
```

**Local Environment:**  
- DevPod Version: 0.5.7
- Operating System: mac
- ARCH of the OS: ARM64 

**DevPod Provider:**  
- Local/remote provider: docker

**Comment by samsaket7** [comment]
I am facing similar issue? @cgestes Were you able to find any resolution?

**Comment by pascalbreuninger** [comment]
Hi @cgestes @samsaket7, this should also be fixed with #1184 and available with the next release

**Comment by eguiraud** [comment]
Hi, this is still broken in the latest version for me: https://github.com/loft-sh/devpod/issues/1234
