### ISSUE TITLE
Permission denied when a try to start existing workspace

### ISSUE THREAD

**Issue by darkterra** [loft-sh/devpod#1271]
**What happened?**  
After successfully creating a workspace, I can no longer start it again if it has been stopped.

![image (1)~2.png](https://github.com/user-attachments/assets/2e145772-470b-4dd6-80f6-61d722ec7e2e)

![image (2)~3.png](https://github.com/user-attachments/assets/acfe5b85-0947-4276-9b34-9c9bb2bbcf06)

![image (3)~2.png](https://github.com/user-attachments/assets/f779fb11-6a1a-4500-baba-d1addb8fdd2e)

---

**What did you expect to happen instead?**  
I expect to be able to start an already created workspace without any permission issue.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Create a docker provider with default values
2. Create a workspace from a remote git repo _(without `.devcontainer.json` file)_ => `devpod up ..../lora.git`
3. Stop the workspace=> `devpod stop lora`
4. Start again the workspace=> `devpod up lora`

My *`devcontainer.json`*:
```
{
    "image": "mrc.microsoft.com/de containers/javascript-node"
}
```

**Local Environment:**  
- DevPod Version: [use `v0.5.16`]
- Operating System: `Linux` _(Ubuntu 20.04)_
- ARCH of the OS: `AMD64`

**DevPod Provider:**  
- Local/remote provider: docker | ssh

**Anything else we need to know?**  
I only use the CLI version of DevPod because on my machine _(Ubuntu 20.04)_ the graphical version does not work I will possibly make another ticket later to try to find a solution.

Otherwise, everything seems to work correctly with the CLI version apart from this permission error when I start an already existing workspace stopped.

I also specify that I am starting from an existing project that does not have an existing `.devcontainer.json` file in the project. So DevPod adds it when creating the workspace.

**Comment by bkneis** [comment]
This should now be fixed in `0.5.21` :)

**Comment by darkterra** [comment]
Thank you very much for your help and the PR!
However, I tried again today after updating DevPod, but from what I see the problem is still present:

![image](https://github.com/user-attachments/assets/9841013b-74c2-4067-86f6-bdf35f92dd20)


I specify that I deleted all the workspaces then I retrieved from gitlab the repo which does not contain a .devcontainer.json file

**Comment by bkneis** [comment]
Hi @darkterra could you perform `devpod delete` instead of `devpod stop` and try again? I can see in the logs it's using the existing workspace so this may cause an issue

**Comment by darkterra** [comment]
I was off to a good start with all workspaces deleted as mentioned in my previous post. But it's true that I showed a condensed version of the actions I performed with the previous image.


Here's an image that shows all the steps of steps.

![DevPod_Issue_#1271.png](https://github.com/user-attachments/assets/80a1d675-9b86-4a74-94ee-01f7853c2b8a)

I hope it will be clearer like this 😇

**Comment by bkneis** [comment]
@darkterra thank you for this, yes that made the issue much clearer thank you. I manage to reproduce the issue properly this time and this is fixed in my PR - https://github.com/loft-sh/devpod/pull/1294

**Comment by bkneis** [comment]
I'll ping you once we release `0.5.22`

**Comment by darkterra** [comment]
Thank you so much !

I have a second issue to report. I'll take care of it quickly, so if it's a real bug _(and not a usability problem on my part)_ the fix can be shipped with version 0.5.22 ?
