### ISSUE TITLE
SSH Provider does not work

### ISSUE THREAD

**Issue by vedhavyas** [loft-sh/devpod#278]
**What happened?**
I added a new SSH provider and then created a Workspace. But workspace was never created. Instead it just keeps on waiting.

**What did you expect to happen instead?**
I thought it would start the dev container

**How can we reproduce the bug?** (as minimally and precisely as possible)
I just downloaded the app to my MacM1. I can connect to SSH provider.

**Local Environment:**

* DevPod Version: 0.12
* Operating System:  mac
* ARCH of the OS: ARM64

**DevPod Provider:**

* Local/remote provider: ssh

**Anything else we need to know?**

**Comment by ThomasK33** [comment]
Hey @vedhavyas 👋 

I just pushed an update for that in the [devpod-provider-ssh](https://github.com/loft-sh/devpod-provider-ssh) repo.

Could you please update your ssh provider and let me know if it works:
- CLI updates `devpod provider update ssh` (or replace ssh with the name of your ssh provider as shown in `devpod provider list`)
- UI update: Remove your old SSH provider and add a new one.

**Comment by vedhavyas** [comment]
@ThomasK33 Still the same. 
Here is what I see from UI

```
[12:11:37] info Creating devcontainer...
[12:11:43] info Waiting for devpod agent to come up...
[12:11:53] info Waiting for devpod agent to come up...
[12:12:02] info Waiting for devpod agent to come up...
```

I dont think SSH connection was made looking at provider host.

**Comment by ThomasK33** [comment]
Hey @vedhavyas, please enable the `Use --debug` flag in the Settings section and post the debug output.

Also, what ssh provider version are you using? (The one is shown in the Providers section below your ssh provider.)

**Comment by ThomasK33** [comment]
What macOS version are you using?
Also, what ssh target OS are you trying to connect to?

**Comment by bketelsen** [comment]
a workaround is to set the shell for the target host's user to bash instead of ssh.

**Comment by ThomasK33** [comment]
Hey there!
I just wanted to give an update on the issue. The problem relates to how zsh and fish handle word splitting compared to bash and sh. Essentially, when we use `sh -c` with zsh, it’s not recognized as a command but rather as a single string or variable, which causes the error message to pop up.

This should be resolved soon™️.

https://zsh.sourceforge.io/FAQ/zshfaq03.html

**Comment by vedhavyas** [comment]
@ThomasK33 This is awesome. Let me know when the fix is deployed and I can test it out.

**Comment by vedhavyas** [comment]
@ThomasK33 Did not work. Here are some logs

```
$ devpod --debug up github.com/subspace/subspace                                                                                                                                                              
14:07:09 info Workspace subspace already exists
14:07:09 info Creating devcontainer...
14:07:09 debug Inject and run command: '/opt/devpod/agent' agent workspace up --workspace-info 'some-base64encoded data' --debug
14:07:09 debug execute inject script
14:07:09 debug Run command provider command: ssh -oStrictHostKeyChecking=no \
    -p ${PORT} \
    ${EXTRA_FLAGS} \
    "${HOST}" \
    "${COMMAND}"
14:07:12 debug curl: (22) The requested URL returned error: 404
14:07:12 debug error: failed to download devpod
14:07:12 debug        command returned: 22
14:07:12 debug Trying again in 10 seconds...
14:07:22 debug curl: (22) The requested URL returned error: 404
14:07:22 debug error: failed to download devpod
14:07:22 debug        command returned: 22
14:07:22 debug Trying again in 10 seconds...
```

Let me know if you need more details

**Comment by ThomasK33** [comment]
Can you try setting the `DEVPOD_AGENT_URL` env variable to `https://github.com/loft-sh/devpod/releases/download/v0.1.5-alpha.2` please?

**Comment by vedhavyas** [comment]
Okay. I ran with the env and its still the same 404 issue. 

> It cannot download the devpod agent on the target host due to some build issues on the GitHub Actions/GitHub Release side.

Okay that explains the 404 :)

**Comment by ThomasK33** [comment]
Yeah, the [release action](https://github.com/loft-sh/devpod/actions/runs/5065930347) fails at building the amd64 Linux binary, so it cannot download it. Arm64 hosts should work, though.

**Comment by vedhavyas** [comment]
okay. I'm gonna close this issue and wait for new release. Will re-open this if the I see any issues again

**Comment by ThomasK33** [comment]
Hey @vedhavyas, could you please check the [0.16.0 release](https://github.com/loft-sh/devpod/releases/tag/v0.1.6). Thank you.

**Comment by vedhavyas** [comment]
I was able to get the container started but it panicked. Here are the logs 
```
agent error: bash: no job control in this shell
bash: /Users/vedhavyas/.docker/init-bash.sh: No such file or directory
Use /root/.devpod/agent/contexts/default/workspaces/subspace as workspace dir
exit status 1
setup container
github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runSingleContainer
        /home/runner/work/devpod/devpod/pkg/devcontainer/single.go:96
github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up
        /home/runner/work/devpod/devpod/pkg/devcontainer/run.go:126
github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp
        /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:374
github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up
        /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:164
github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
        /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:98
github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
        /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:60
github.com/spf13/cobra.(*Command).execute
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
github.com/loft-sh/devpod/cmd.Execute
        /home/runner/work/devpod/devpod/cmd/root.go:71
main.main
        /home/runner/work/devpod/devpod/main.go:12
runtime.main
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/proc.go:250
runtime.goexit
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/asm_amd64.s:1594
devcontainer up
github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
        /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:100
github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
        /home/runner/work/devpod/devpod/cmd/agent/workspace/up.go:60
github.com/spf13/cobra.(*Command).execute
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        /home/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
github.com/loft-sh/devpod/cmd.Execute
        /home/runner/work/devpod/devpod/cmd/root.go:71
main.main
        /home/runner/work/devpod/devpod/main.go:12
runtime.main
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/proc.go:250
runtime.goexit
        /opt/hostedtoolcache/go/1.19.9/x64/src/runtime/asm_amd64.s:1594

github.com/loft-sh/devpod/pkg/agent.InjectAgentAndExecute
        /Users/runner/work/devpod/devpod/pkg/agent/inject.go:119
github.com/loft-sh/devpod/cmd.(*UpCmd).devPodUpMachine.func1
        /Users/runner/work/devpod/devpod/cmd/up.go:262
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.19.9/x64/src/runtime/asm_arm64.s:1172
```

I also noticed that enabling injecting docker credentials also panics for some reason and I do not have a log for it.

If this is unrelated to this, I can open another issue with this

**Comment by mistercorea** [comment]
I actually have this issue. I am from and targeting Mac Monterey. 
eventually I want to have my mac at home and will use like Mac Air or chromebook
